### ISSUE TITLE
How to update spec and status

### ISSUE THREAD

**Issue by Young-china** [kubernetes-sigs/apiserver-builder-alpha#469]
Hi,

It's stupid question,  but I really need your help.

I'm trying to update the `Spec` and `Status` in Reconcile code, and only `Spec` were updated.

The apiserver-builder-alpha release is  `v1.16.alpha.1`

Here is my code:

```
func (r *ReconcileMachine) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	// Fetch the Machine instance
	instance := &adav1.Machine{}
	err := r.Get(context.TODO(), request.NamespacedName, instance)
	if err != nil {
		if errors.IsNotFound(err) {
			// Object not found, return.  Created objects are automatically garbage collected.
			// For additional cleanup logic use finalizers.
			return reconcile.Result{}, nil
		}
		// Error reading the object - requeue the request.
		return reconcile.Result{}, err
	}

	// machine deepcopy
	md := instance.DeepCopy()
	md.Status.Status = "ready"
	md.Spec.IP = "127.0.0.1"
        err = r.Update(context.TODO(), md)
}
```

My question is:
- What is the right way to update `Spec` and `Status`?
- Should I use `DeepCopy` before update?

I would appreciate you very much if can give an answer or just give me a guideline link.

**Comment by yue9944882** [comment]
> What is the right way to update Spec and Status?

yes, this is the expected behavior. `spec` and `status` are updated separatedly. moreover, the status update is supposed to be done by requesting corresponding sub-resource e.g.

https://github.com/kubernetes-sigs/controller-runtime/blob/4ba0a3b63c8580e39afb413da3209f5ffcb6b278/pkg/client/client.go#L182-L185

> Should I use DeepCopy before update?

it depends on whether the instance is get from the cache or the real request payload. for the former case, yes, i think you should deepcopy in order to avoid mutating the cache entries. as for the latter, you're free to do in-place modification upon the resource.
