### ISSUE TITLE
init repo not working with Go Modules

### ISSUE THREAD

**Issue by clarkmcc** [kubernetes-sigs/apiserver-builder-alpha#519]
I'm trying to run `apiserver-boot init repo` but I keep getting the error

```sh
apiserver-boot must be run from the directory containing the go package to bootstrap. This must be under $GOPATH/src/<package>. 
```

Is there a reason that I can't run this in a go module?

**Comment by yue9944882** [comment]
thanks for reporting this, will open a fix soon

**Comment by drewwells** [comment]
Any updates on this?

**Comment by drewwells** [comment]
/remove-lifecycle stale
bump

**Comment by jaredhancock31** [comment]
can we revive this

**Comment by clarkmcc** [comment]
@jaredhancock31 This project seems to be unmaintained, I found that https://github.com/kcp-dev/kcp worked as a replacement for this and has the added benefit of working nicely with the kubebuilder project.

**Comment by jaredhancock31** [comment]
I'm looking for the basic skeleton required to register an aggregation APIServer which does not require any storage, etcd or otherwise. Previously I was using the generators provided by this project, but now that this and `apiserver-runtime` are not maintained, it's not super obvious to me which pieces need to taped together in order to achieve that. Not seeing any mention of that in the `kcp` project either unfortunately. Any guidance on this matter would be much appreciated. 

Until then, I guess I'll keep digging :)

**Comment by yang-wei** [comment]
You can add `--module-name` for module to work. As instructed in the CLI
```
apiserver-boot -h

# Initialize your repository with scaffolding directories and go files. Specify --module-name if the project works outside GOPATH.
apiserver-boot init repo --domain example.com

```

**Comment by turkenh** [comment]
> You can add `--module-name` for module to work. As instructed in the CLI
> 
> ```
> apiserver-boot -h
> 
> # Initialize your repository with scaffolding directories and go files. Specify --module-name if the project works outside GOPATH.
> apiserver-boot init repo --domain example.com
> ```

👆 This. 
Thanks a lot @yang-wei 👍
