### ISSUE TITLE
Generate and register new storage backend

### ISSUE THREAD

**Issue by pires** [kubernetes-sigs/apiserver-builder-alpha#98]
This is a **feature request**.

Right now, `StartApiServer` flow is highly opinionated about a few things like the storage backend to be used (enforces `etcd`) or the options passed onto the _apiserver_. While this allows the apiserver to work out-of-the box rather easily, it limits more advanced scenarios, like implementing your own storage layer and easily point to it.

I suggest implementing a generator for a new storage layer, i.e. `apiserver-boot create storage --name=xyz` that generates stub code for `xyz` in `pkg/storage/xyz` and some code in `cmd/apiserver` that points out how it can be configured and enabled.

**Comment by pwittrock** [comment]
@pires Would you be interested in implementing this?

**Comment by pires** [comment]
Yes. I should be able to pick it up during the last couple weeks of August.

**Comment by klustria** [comment]
Any updates on this? Is this kind of related to this issue/question I posted: https://github.com/kubernetes-incubator/apiserver-builder/issues/226 ?

**Comment by pires** [comment]
Yes it is. And I think I can spare some cycles in the next couple months for this.

**Comment by klustria** [comment]
Appreciate your response. If you don't mind, can you give me an overview of what you intend to do. Details would be good too. I'm trying to look around for any links that can provide me ideas how to implement but I can't seem to find any. If you have any of those, would appreciate if you can share it with me. I've been trying to look for this topic to justify the use of API-Server aggregation in our project as some people in the team are kind of reluctant with ETCD, so our plan is to try other persistence mechanism. So would appreciate if you can share your ideas about this. TIA.

**Comment by klustria** [comment]
As I'm reviewing the k8s.io/apiserver code, it looks like storage.Interface is the one used for implementing the storage. pkg/registry/generic/NewRawStorage() is the one that instantiates the actual storage. However from looking at factory.Create in NewRawStorage(), it looks like it only supports ETCD and ETCD3. Unless my understanding is wrong, etcd seems to be hardcoded into the apiserver code without an opportunity to pass a custom implementation of storage.Interface. So as a question, is there another way to do this, i.e. implement your own custom storage.Interface and be able use it in the aggregated api server? Would appreciate if you can share your thoughts if have ideas regarding this already. I'm really eager to get some answers to this question, so I can justify the use of the aggregated api-server to my team who wants to use another persistent storage instead of etcd. TIA.

**Comment by pires** [comment]
Not really, @klustria. While, conceptually, supporting a different storage engine makes sense, the fact is [`kubernetes/apiserver` library](https://github.com/kubernetes/apiserver/tree/master/pkg/storage) is very opinionated about using etcd.

But [here's an idea](https://github.com/kubernetes/features/issues/172#issuecomment-337324147). There's a related gdoc link in the same comment and it might worth a try.

**Comment by pires** [comment]
It seems the [metrics-server](https://github.com/kubernetes-incubator/metrics-server) proves it can be done! In this case, metrics are stored in-memory and no etcd is involved.

**Comment by pires** [comment]
If anyone is still interested in following-up, maybe inspiration can be taken from how [k3s](https://github.com/rancher/k3s) relies on [kvsql](https://github.com/ibuildthecloud/kvsql) to provide support for different storage backends.

**Comment by yue9944882** [comment]
/remove-lifecycle rotten

@pires interesting point, i opened #362 to track this feature

**Comment by drewwells** [comment]
Documentation would at least be useful here. There's a single example of non-etcd but there's no examples of how to use it.
